# Generated by Django 3.1.5 on 2021-01-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='number',
            field=models.CharField(default=134, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='number',
            name='type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('WhatsApp', 'Whatsapp'), ('Telegram', 'Telegram')], default='Phone', max_length=30),
        ),
    ]
