# Generated by Django 3.1.5 on 2021-01-31 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210130_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='number',
        ),
        migrations.AddField(
            model_name='number',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered                                       in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='number',
            name='type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('WhatsApp', 'Whatsapp'), ('Telegram', 'Telegram')], default='Phone', max_length=30),
        ),
    ]
