# Generated by Django 3.1.5 on 2021-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210131_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='number',
            name='type',
            field=models.CharField(choices=[('Phone', 'Phone'), ('WhatsApp', 'Whatsapp'), ('Telegram', 'Telegram')], default='Phone', max_length=30),
        ),
    ]
